# Generated by Django 2.0.4 on 2019-02-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.TextField(verbose_name='Название вакансии')),
                ('salary', models.IntegerField(verbose_name='Зарплата')),
                ('loc', models.TextField(verbose_name='Города, где требуется')),
                ('req', models.TextField(verbose_name='Требования')),
                ('resp', models.TextField(verbose_name='Основные обязанности')),
                ('cond', models.TextField(verbose_name='Предлагаем')),
                ('contact', models.TextField(verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Вакансию',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
