# Generated by Django 2.0.4 on 2019-02-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название акции')),
                ('preview', models.TextField(verbose_name='Описание акции')),
                ('date', models.DateField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Акцию',
                'verbose_name_plural': 'Акции',
            },
        ),
    ]
