# Generated by Django 2.0.4 on 2019-02-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20190219_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='desc',
            field=models.TextField(verbose_name='Комментарий к услуге'),
        ),
    ]
