# Generated by Django 2.0.4 on 2019-02-23 09:09

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20190219_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(validators=[services.models.Service.validate_price], verbose_name='Минимальная цена'),
        ),
    ]
