# Generated by Django 2.0.4 on 2019-02-24 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20190223_1909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
