# Generated by Django 2.0.4 on 2019-02-17 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(verbose_name='Название пункта работы')),
            ],
            options={
                'verbose_name': 'Пункт работы',
                'verbose_name_plural': 'Пункты работы',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название услуги')),
                ('desc', models.TextField(verbose_name='Комментарий к комплексу услуг')),
                ('price', models.IntegerField(verbose_name='Минимальная цена')),
                ('note', models.TextField(verbose_name='Примечание')),
                ('warn', models.TextField(verbose_name='Предупреждение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Category')),
                ('items', models.ManyToManyField(related_name='items_service', to='services.Item', verbose_name='Пункты работы')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
