# Generated by Django 2.0.4 on 2019-03-04 06:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата публикации')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('preview', models.TextField(verbose_name='Содержание')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('related', models.ManyToManyField(blank=True, related_name='_news_related_+', to='news.News', verbose_name='Ссылки на другие новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
