# Generated by Django 2.0.4 on 2019-02-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='job',
            field=models.CharField(max_length=30, verbose_name='Название вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='loc',
            field=models.CharField(max_length=50, verbose_name='Города, где требуется'),
        ),
    ]
