# Generated by Django 2.0.4 on 2019-02-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomend', '0007_auto_20190221_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomend',
            name='url',
            field=models.ImageField(upload_to='recomend', verbose_name='Фотография сертификата'),
        ),
    ]
