# Generated by Django 2.0.4 on 2019-02-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomend', '0008_auto_20190221_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomend',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название организации'),
        ),
    ]
