# Generated by Django 2.0.4 on 2019-02-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sertificate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sertificate',
            name='subt',
            field=models.CharField(max_length=30, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название сертификата'),
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='usl',
            field=models.ImageField(upload_to='Sertificate', verbose_name='Фотография сертификата'),
        ),
    ]
