# Generated by Django 2.0.4 on 2019-03-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='certificate', verbose_name='Фотография сертификата')),
                ('title', models.CharField(max_length=30, verbose_name='Название сертификата')),
                ('subt', models.CharField(max_length=30, verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
    ]
