# Generated by Django 2.0.4 on 2019-02-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usl', models.ImageField(upload_to='', verbose_name='Фотография сертификата')),
                ('title', models.TextField(verbose_name='Название сертификата')),
                ('subt', models.TextField(verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
    ]
