# Generated by Django 2.0.4 on 2019-02-21 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_auto_20190219_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='usl',
            new_name='url',
        ),
    ]
