# Generated by Django 2.0.4 on 2019-02-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20190217_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='cover',
            field=models.ImageField(upload_to='Gallery', verbose_name='Фото на фон'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='Gallery', verbose_name='Фотография'),
        ),
    ]
