# Generated by Django 2.0.4 on 2019-02-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20190219_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='gallery', verbose_name='Фотография'),
        ),
    ]
