# Generated by Django 2.0.4 on 2019-02-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название акции'),
        ),
    ]
